import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { SiteFooter } from "@/components/site-footer";
import { absoluteUrl } from "@/lib/site";
import styles from "../what-electric-toothbrush-should-you-buy/page.module.css";

const canonicalPath = "/home/home-printer-guide";
const title = "Laser, Inkjet, or Tank? Start Here.";
const seoTitle = "Home Printer Buying Guide: Laser vs Inkjet vs Tank | Kumia Labs";
const subtitle = "Five home printer setups based on what you print, how often you print, and what you’ll keep buying afterward.";

export const metadata: Metadata = {
  title: seoTitle,
  description: subtitle,
  alternates: { canonical: canonicalPath },
  openGraph: { title: seoTitle, description: subtitle, url: canonicalPath, type: "article", publishedTime: "2026-09-14", authors: ["Kumia"], images: [absoluteUrl("/images/kumia-printer-guide-card.svg")] },
};

type Product = { role: string; name: string; details: string; why: string; watch: string; url: string; source: string };
type Setup = { number: string; slug: string; title: string; persona: string; lead: string; image: string; imageAlt: string; ownership: [string, string][]; reasoning: string[]; products: Product[] };

const setups: Setup[] = [
  {
    number: "01", slug: "mostly-black-documents", title: "Mostly black documents", persona: "A household that mainly prints forms, shipping labels, school text, and other black-and-white documents", lead: "Brother monochrome laser is Kumia’s preferred starting point for this workflow.", image: "/images/kumia-printer-mono.svg", imageAlt: "An unbranded monochrome laser printer producing a text document",
    ownership: [["Print type", "Monochrome laser"], ["Supply system", "TN830 / TN830XL toner + DR830 drum"], ["Paper capacity", "250 sheets"], ["Auto duplex", "Yes, printing"], ["Scan / ADF", "Choose by model"], ["Maintenance note", "Toner and drum are separate parts"]],
    reasoning: ["Laser printing suits households that care about crisp text and may leave the printer idle between document jobs. Toner is a dry powder, so there is less concern about liquid ink drying at the print head during a quiet month.", "These three Brother models share the same basic print engine and supply family. The useful decision is workflow. HL-L2460DW is print-only. DCP-L2647DW adds a flatbed, copy function, and 50-sheet single-sided ADF. MFC-L2820DW adds fax for households that still need it.", "All three provide automatic two-sided printing and a 250-sheet tray. That is a more meaningful ownership difference than chasing photo features in a printer intended for black documents."],
    products: [
      { role: "Print-only", name: "Brother HL-L2460DW", details: "Monochrome laser, auto duplex, 250-sheet tray", why: "The least complicated option when scanning and copying happen elsewhere.", watch: "No scanner, copier, ADF, or fax.", url: "https://www.brother-usa.com/products/hll2460dw", source: "Brother" },
      { role: "Recommended", name: "Brother DCP-L2647DW", details: "Print, scan, copy, 50-sheet ADF, auto duplex print", why: "Adds the document tools most homes are likely to use without paying for fax.", watch: "ADF scanning is single-sided.", url: "https://www.brother-usa.com/p/laser-printers/DCPL2647DW", source: "Brother" },
      { role: "Full office", name: "Brother MFC-L2820DW", details: "Print, scan, copy, fax, 50-sheet ADF", why: "Fits a home workflow that still receives or sends faxes.", watch: "Fax is unnecessary cost if you will never connect a phone line.", url: "https://www.brother-usa.com/products/mfcl2820dw", source: "Brother" },
    ],
  },
  {
    number: "02", slug: "occasional-color", title: "Occasional color, lower upfront cost", persona: "Someone who prints a few color forms, recipes, tickets, or school pages and wants a low purchase price", lead: "A cartridge inkjet can still make sense when print volume is low and the upfront budget matters most.", image: "/images/kumia-printer-color.svg", imageAlt: "An unbranded compact color inkjet printer producing a colorful page",
    ownership: [["Print type", "Color inkjet"], ["Supply system", "Replaceable cartridges"], ["Paper capacity", "100 to 150 sheets"], ["Auto duplex", "Yes"], ["Scan / ADF", "Flatbed; Brother adds 20-sheet ADF"], ["Cost note", "Lower entry price, higher cost per page"]],
    reasoning: ["Cartridge printers ask for less money on day one. For a household that prints only occasionally, that can matter more than reaching the lowest possible cost per page over thousands of sheets.", "Brother’s MFC-J1360DW is the most document-ready option here because it includes a 150-sheet tray and a 20-page ADF. Epson’s XP-5200 is compact and straightforward for scan, copy, and color printing. HP’s Envy 6155 centers on simple home printing and mobile setup with a 100-sheet tray.", "The tradeoff is supply cost. Small cartridges need replacement more often than bottles, and infrequent liquid-ink printing still benefits from running a page periodically so the print system does not sit unused for long stretches."],
    products: [
      { role: "Recommended", name: "Brother MFC-J1360DW", details: "Color all-in-one, 150-sheet tray, 20-page ADF", why: "The strongest paper and scanning setup in this low-cost group.", watch: "Starter cartridges are modest, and replacement cartridge cost matters with frequent use.", url: "https://www.brother-usa.com/p/inkjet-printers/MFCJ1360DW", source: "Brother" },
      { role: "Compact", name: "Epson Expression Home XP-5200", details: "Color print, scan, copy, auto duplex", why: "A compact home option when flatbed scanning is enough.", watch: "No ADF, and cartridges are not the lowest-cost supply system.", url: "https://epson.com/For-Home/Printers/Inkjet/Expression-Home-XP-5200-Wireless-Color-Inkjet-All-in-One-Printer-with-Scan-and-Copy/p/C11CK61201", source: "Epson" },
      { role: "Simple setup", name: "HP Envy 6155", details: "Color print, scan, copy, mobile fax, 100-sheet tray", why: "Useful for a household already comfortable with HP’s app and cartridge ecosystem.", watch: "No ADF. Dynamic-security and optional subscription terms deserve a read before buying.", url: "https://www.hp.com/us-en/shop/pdp/hp-envy-6155e-all-in-one-printer", source: "HP" },
    ],
  },
  {
    number: "03", slug: "family-printing", title: "Family printing", persona: "A household printing worksheets, color documents, schedules, and school projects every week", lead: "Regular family printing is where refillable tanks begin to earn their space.", image: "/images/kumia-printer-family.svg", imageAlt: "An unbranded refillable-tank printer producing household worksheets",
    ownership: [["Print type", "Color refillable tank"], ["Supply system", "Ink bottles"], ["Paper capacity", "100 to 150 sheets"], ["Auto duplex", "Epson and Brother: yes"], ["Scan / ADF", "Flatbed only"], ["Maintenance note", "Print regularly and keep tanks above minimum levels"]],
    reasoning: ["Bottle-fed printers cost more up front, but their included ink and high replacement yields suit a family that expects steady page volume. Refilling a tank is less frequent than replacing small cartridges.", "Epson ET-2980 and Brother MFC-T580DW both add automatic two-sided printing. Brother has the larger 150-sheet tray and a three-year limited warranty. Canon G3270 is the simpler value alternative, with a 100-sheet rear tray and no automatic duplex.", "None of these three has an ADF. That is acceptable for occasional flatbed scans, but a household regularly copying multi-page packets should move to the home-office setup."],
    products: [
      { role: "Recommended", name: "Epson EcoTank ET-2980", details: "Refillable tank, print, scan, copy, auto duplex, 100-sheet tray", why: "A balanced family machine with duplex printing and a documented high-yield bottle system.", watch: "No ADF, and the tray is smaller than the Brother option.", url: "https://epson.com/For-Home/Printers/Inkjet/EcoTank-ET-2980-Wireless-All-in-One-Color-Supertank-Printer-%E2%80%93-Black/p/C11CL41201", source: "Epson" },
      { role: "More paper", name: "Brother MFC-T580DW", details: "Refillable tank, 150-sheet tray, auto duplex, print, scan, copy", why: "The larger tray and three-year warranty fit a busy family desk.", watch: "Flatbed scanning only; no ADF.", url: "https://www.brother-usa.com/p/inkjet-printers/MFCT580DW", source: "Brother" },
      { role: "Value", name: "Canon PIXMA MegaTank G3270", details: "Refillable tank, print, scan, copy, 100-sheet rear tray", why: "A current, compact MegaTank route into low-frequency bottle refills.", watch: "Manual two-sided printing and no ADF.", url: "https://www.usa.canon.com/shop/p/pixma-g3270", source: "Canon" },
    ],
  },
  {
    number: "04", slug: "home-office", title: "Home office", persona: "Someone printing regular business documents and scanning multi-page paperwork", lead: "A home-office printer earns its keep through paper handling and scanning workflow.", image: "/images/kumia-printer-office.svg", imageAlt: "An unbranded home-office printer with an automatic document feeder",
    ownership: [["Print type", "Color tank or business inkjet"], ["Supply system", "Bottles or cartridges"], ["Paper capacity", "150 to 250 sheets"], ["Auto duplex", "Yes, printing"], ["Scan / ADF", "20 to 35 sheets"], ["Workflow note", "Check whether duplex scanning is required"]],
    reasoning: ["Multi-page scanning changes this category. An ADF lets a contract or packet move through without lifting the scanner lid for every sheet. A larger paper tray also reduces interruptions during ordinary work weeks.", "Epson ET-3950 pairs refill bottles with a 250-sheet tray and ADF. Brother MFC-T780DW uses bottles too, with a 150-sheet tray and 20-page ADF. HP OfficeJet Pro 9125 uses cartridges, but offers a 250-sheet tray, 35-sheet ADF, fax, Ethernet, and faster office-oriented output.", "The tank models favor lower supply frequency. HP favors a conventional office feature set and asks the owner to accept cartridge costs and HP’s supply policies."],
    products: [
      { role: "Recommended", name: "Epson EcoTank ET-3950", details: "Refillable tank, 250-sheet tray, ADF, auto duplex", why: "Combines tank ownership with the paper capacity expected from a home office.", watch: "Confirm live stock, and check scanner details if two-sided originals are routine.", url: "https://epson.com/For-Home/Printers/Inkjet/EcoTank-ET-3950-Wireless-All-in-One-Color-Supertank-Printer-%E2%80%93-White/p/C11CL43201", source: "Epson" },
      { role: "Tank alternative", name: "Brother MFC-T780DW", details: "Refillable tank, 150-sheet tray, 20-page ADF, auto duplex", why: "A clear bottle-fed alternative with a three-year limited warranty.", watch: "The tray and ADF are smaller than the other two options.", url: "https://www.brother-usa.com/p/inkjet-printers/MFCT780DW", source: "Brother" },
      { role: "Office features", name: "HP OfficeJet Pro 9125", details: "Cartridge inkjet, 250-sheet tray, 35-sheet ADF, fax, Ethernet", why: "Fits a workflow that values office connectivity and document handling over tank refills.", watch: "Cartridge ownership and dynamic-security terms differ from the tank options.", url: "https://www.hp.com/us-en/shop/pdp/hp-officejet-pro-9125e-all-in-one-printer", source: "HP" },
    ],
  },
  {
    number: "05", slug: "photos-creative", title: "Photos and creative projects", persona: "Someone intentionally printing photographs, artwork, crafts, or large visual projects", lead: "Photo printing needs a printer built around color range and media handling.", image: "/images/kumia-printer-photo.svg", imageAlt: "An unbranded six-color photo printer producing a colorful print",
    ownership: [["Print type", "Photo inkjet"], ["Supply system", "Six-color bottles or 10-ink pigment set"], ["Maximum size", "8.5 × 11, 13 × 19"], ["Auto duplex", "Epson: yes; Canon PRO-310: no"], ["Scan / copy", "Epson only"], ["Commitment note", "Media and ink choice shape the result"]],
    reasoning: ["Epson’s ET-8500 and ET-8550 use six-color refillable ink systems and still work as all-in-one home printers. ET-8500 is the letter-size choice. ET-8550 adds wide-format printing up to 13 by 19 inches.", "Canon imagePROGRAF PRO-310 is a different commitment. It is a print-only 13-inch professional photo printer with nine pigment inks plus Chroma Optimizer. It asks for more individual cartridges and careful media choices in return for a more specialized fine-art workflow.", "Choose the maximum print size first. Then decide whether the same machine also needs to scan documents. A photo-focused purchase should be driven by the work you plan to print, rather than treating an ordinary four-color office inkjet as equivalent."],
    products: [
      { role: "Letter-size", name: "Epson EcoTank Photo ET-8500", details: "Six-color refillable ink, all-in-one, borderless up to 8.5 × 11", why: "Good for a home that wants photo capability without giving up scan and copy.", watch: "Letter-size maximum is limiting for larger artwork.", url: "https://epson.com/For-Work/Printers/Inkjet/EcoTank-Photo-ET-8500-Wireless-Color-All-in-One-Supertank-Printer/p/C11CJ20201", source: "Epson" },
      { role: "Wide-format", name: "Epson EcoTank Photo ET-8550", details: "Six-color refillable ink, all-in-one, prints up to 13 × 19", why: "Adds wide-format output while retaining tank refills and scanning.", watch: "The larger chassis and higher purchase price only pay off if wide prints matter.", url: "https://epson.com/For-Work/Printers/Inkjet/EcoTank-Photo-ET-8550-All-in-One-Wide-format-Supertank-Printer/p/C11CJ21201", source: "Epson" },
      { role: "Professional", name: "Canon imagePROGRAF PRO-310", details: "13-inch print-only photo printer, nine pigment inks plus Chroma Optimizer", why: "The specialized option for photographers and artists who prioritize pigment output and media control.", watch: "No scan, copy, or duplex. Ten separate consumables make this a serious ownership commitment.", url: "https://www.usa.canon.com/shop/p/imageprograf-pro-310", source: "Canon" },
    ],
  },
];

const comparisonRows = [
  ["01 Black documents", "Mono laser", "Toner + drum", "No", "Yes", "Model dependent", "Text and forms"],
  ["02 Occasional color", "Color inkjet", "Cartridges", "Yes", "Yes", "Brother only", "Low upfront cost"],
  ["03 Family", "Color inkjet", "Bottles", "Yes", "Model dependent", "No", "Regular household use"],
  ["04 Home office", "Color inkjet", "Bottles / cartridges", "Yes", "Yes", "Yes", "Documents and scanning"],
  ["05 Photo", "Photo inkjet", "6-color bottles / pigment cartridges", "Yes", "Model dependent", "Epson only", "Photos and art"],
];

function Header() { return <header className="site-header article-site-header"><Link className="brand-lockup" href="/" aria-label="Kumia Labs home"><Image src="/brand/kumia-k-mark.png" alt="" width={40} height={40}/><span className="header-wordmark"><b>Kumia</b><b>Labs</b></span></Link><nav className="desktop-nav" aria-label="Primary navigation"><Link href="/#latest">Research</Link><Link href="/#latest">Home</Link><Link href="/#meet-kumia">About</Link></nav></header>; }
function ProductCard({ product }: { product: Product }) { return <article className={styles.productCard}><p>{product.role} · {product.source}</p><h4>{product.name}</h4><p className={styles.details}>{product.details}</p><dl><div><dt>Why pick it</dt><dd>{product.why}</dd></div><div><dt>Watch for</dt><dd>{product.watch}</dd></div></dl><a href={product.url} target="_blank" rel="noopener noreferrer">View official product <span aria-hidden="true">→</span></a></article>; }
function SetupSection({ setup }: { setup: Setup }) { return <section id={setup.slug} className={styles.setup} aria-labelledby={`${setup.slug}-title`}><header><span>{setup.number}</span><div><p>SETUP {setup.number}</p><h2 id={`${setup.slug}-title`}>{setup.title}</h2></div></header><figure><Image src={setup.image} alt={setup.imageAlt} width={1600} height={900} sizes="(max-width: 700px) 100vw, 1120px"/></figure><div className={styles.ownership}><p className={styles.eyebrow}>WHAT OWNERSHIP LOOKS LIKE</p><h3>Supplies, paper, and daily workflow</h3><dl>{setup.ownership.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></div><div className={styles.who}><p className={styles.eyebrow}>WHO IT&rsquo;S FOR</p><h3>{setup.persona}</h3></div><div className={styles.reasoning}><h3>Why this combination works</h3><div><p className={styles.reasoningLead}>{setup.lead}</p>{setup.reasoning.map(text=><p key={text}>{text}</p>)}</div></div><section className={styles.readyMade} aria-labelledby={`${setup.slug}-products`}><h3 id={`${setup.slug}-products`}>Ready-made options</h3><p>Models and availability were checked on September 14, 2026. Confirm the live manufacturer page before buying.</p><div>{setup.products.map(product=><ProductCard key={product.name} product={product}/>)}</div></section></section>; }

export default function HomePrinterGuide() {
  const articleJsonLd = { "@context":"https://schema.org", "@type":"Article", headline:title, description:subtitle, datePublished:"2026-09-14", dateModified:"2026-09-14", author:{"@type":"Person",name:"Kumia"}, publisher:{"@type":"Organization",name:"Kumia Labs",url:absoluteUrl()}, mainEntityOfPage:absoluteUrl(canonicalPath), image:absoluteUrl("/images/kumia-printer-guide-card.svg") };
  const breadcrumbJsonLd = { "@context":"https://schema.org", "@type":"BreadcrumbList", itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:absoluteUrl()},{"@type":"ListItem",position:2,name:"Home research",item:absoluteUrl("/#latest")},{"@type":"ListItem",position:3,name:title,item:absoluteUrl(canonicalPath)}] };
  return <main className={styles.page}><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleJsonLd).replaceAll("<","\\u003c")}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbJsonLd).replaceAll("<","\\u003c")}}/><Header/><article><div className={styles.breadcrumb}><Link href="/">Home</Link><span>/</span><Link href="/#latest">Home research</Link><span>/</span><span>Home printer guide</span></div><header className={styles.hero}><h1 className="sr-only">{title}</h1><figure><Image src="/images/kumia-printer-guide-card.svg" alt="Temporary Kumia Labs home printer guide cover" width={1600} height={900} sizes="100vw" priority/></figure></header><div className={styles.content}>
    <section className={styles.intro} aria-label="Introduction"><div><Image src="/images/kumia-intro-pointing-transparent.png" alt="Kumia" width={1122} height={1402} sizes="(max-width:600px) 88px,140px"/></div><p>A printer is also a supply system, a paper tray, and a maintenance routine. Start with what your household prints and how often, then choose the machine you will still want to own after the starter ink or toner is gone.</p></section>
    <section className={styles.comparison} aria-labelledby="quick-comparison"><div className={styles.sectionHeading}><p>AT A GLANCE</p><h2 id="quick-comparison">Quick comparison</h2></div><div className={styles.tableScroll}><table><thead><tr>{["Setup","Print type","Supply system","Color","Auto duplex","ADF","Best for"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{comparisonRows.map(row=><tr key={row[0]}>{row.map((cell,i)=>i===0?<th scope="row" key={`${row[0]}-${i}`}>{cell}</th>:<td key={`${row[0]}-${i}`}>{cell}</td>)}</tr>)}</tbody></table></div></section>
    <nav className={styles.index} aria-label="Five home printer setups"><p className={styles.eyebrow}>FIVE SETUPS AT A GLANCE</p><ol>{setups.map(setup=><li key={setup.slug}><span>{setup.number}</span><div><strong>{setup.title}</strong><p>{setup.persona}</p></div><a href={`#${setup.slug}`} aria-label={`Jump to ${setup.title}`}>↓</a></li>)}</ol></nav>
    {setups.map(setup=><SetupSection key={setup.slug} setup={setup}/>)}
    <section className={styles.cost} aria-labelledby="supply-cost"><div className={styles.sectionHeading}><p>OWNERSHIP SNAPSHOT · 2026.09.14</p><h2 id="supply-cost">Supply and running cost</h2></div><p>Manufacturer yield claims make the scale of each system clear, but they do not produce one universal cost-per-page figure. Coverage, cleaning cycles, draft settings, photo paper, and current bottle or cartridge prices all change the result.</p><div className={styles.tableScroll}><table><thead><tr>{["System","Verified yield example","What the owner replaces","Cost reading"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody><tr><th>Brother mono laser</th><td>Starter toner varies by model; DR830 drum rated around 15,000 pages</td><td>Toner, then drum at a longer interval</td><td>Good document economics; calculate from the live TN830 price</td></tr><tr><th>Canon G3270 tank</th><td>Up to 6,000 black / 7,700 color pages per full set</td><td>GI-21 bottles; print head and maintenance cartridge are replaceable</td><td>High yield, but photo coverage changes real-world cost</td></tr><tr><th>Brother MFC-T580DW</th><td>Included black ink up to 7,125 pages; color up to 4,400</td><td>Ink bottles</td><td>Long intervals between routine refills for family documents</td></tr><tr><th>Epson ET-8500</th><td>Epson estimates about 4 cents per 4 × 6 photo using ink only</td><td>Six ink bottles plus media</td><td>Paper cost must be added; not comparable to document CPP</td></tr><tr><th>Canon PRO-310</th><td>No reliable single page-cost figure used here</td><td>Nine pigment inks plus Chroma Optimizer and photo media</td><td>Specialized output, with materially higher supply commitment</td></tr></tbody></table></div><p className={styles.note}>Prices and availability were checked September 14, 2026 and may change. Kumia Labs did not invent a cost-per-page estimate where current manufacturer price and yield data were not directly comparable.</p></section>
    <section className={styles.choose} aria-labelledby="how-to-choose"><div className={styles.sectionHeading}><p>HOW TO CHOOSE</p><h2 id="how-to-choose">Start with the pages you actually print</h2></div><div><p>Choose monochrome laser when almost every page is black text and long idle periods are common. Choose a low-cost cartridge inkjet when color is occasional and the purchase price matters more than long-run page cost.</p><p>Move to a refillable tank when the household prints regularly. Add an ADF and larger tray when multi-page documents are part of work. For photos, choose the useful print size and ink system before comparing general office features.</p><p>Finally, price the exact supplies available near you. Check whether toner and drum are separate, whether an ink subscription is optional, and whether replacement bottles or cartridges remain easy to find.</p></div></section>
    <aside className={styles.closing} aria-label="Kumia's closing note"><Image src="/images/kumia-conclusion-clasped-transparent.png" alt="Kumia" width={1122} height={1402} sizes="(max-width:600px) 88px,126px"/><p>Buy for the pages you print most often. The right printer is the one whose supplies, paper handling, and maintenance still make sense after the box is open.</p></aside>
    <section className={styles.sources} aria-labelledby="sources"><h2 id="sources">Sources and methodology</h2><p>Specifications, availability, yields, and price snapshots were checked on September 14, 2026. Current US manufacturer product pages and support specifications were prioritized.</p><ul>{setups.flatMap(s=>s.products).map(p=><li key={p.name}><a href={p.url}>{p.source}: {p.name}</a></li>)}</ul></section>
  </div></article><SiteFooter/></main>;
}
